[package]
name = "parse-display-derive"
version = "0.8.2"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/frozenlib/parse-display"
documentation = "https://docs.rs/parse-display/"
keywords = ["derive", "enum", "from_str", "display", "regex"]
categories = ["parsing"]
description = "Procedural macro to implement Display and FromStr using common settings."
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.39", features = ["visit"] }
quote = "1.0.33"
proc-macro2 = "1.0.70"
regex = "1.10.2"
regex-syntax = "0.8.2"
structmeta = "0.2.0"
