[package]
name = "parse-display-derive"
version = "0.8.1"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/frozenlib/parse-display"
documentation = "https://docs.rs/parse-display/"
keywords = ["derive", "enum", "from_str", "display", "regex"]
categories = ["parsing"]
description = "Procedural macro to implement Display and FromStr using common settings."
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.13", features = ["visit"] }
quote = "1.0.26"
proc-macro2 = "1.0.55"
regex = "1.7.3"
regex-syntax = "0.6.29"
once_cell = "1.17.1"
structmeta = "0.2.0"
