[package]
name = "parse-display"
version = "0.5.2"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/frozenlib/parse-display"
documentation = "https://docs.rs/parse-display/"
keywords = ["derive", "enum", "from_str", "display", "regex"]
categories = ["parsing"]
description = "Procedural macro to implement Display and FromStr using common settings."
edition = "2018"

[dependencies]
parse-display-derive = { version = "=0.5.2", path = "../parse-display-derive" }
once_cell = { version = "1.7.2", optional = true }
regex = { version = "1.4.5", optional = true }

[features]
default = ["std", "regex", "once_cell"]
std = []
