name: CI

on:
  push:
  pull_request:
  schedule: [cron: "20 5 * * *"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Build tests
        run: cargo test --verbose --no-run
      - name: Run tests
        run: cargo test --verbose

      - name: Build no-std
        run: cargo build --verbose --target-dir=target/no-std --no-default-features
      - name: Build tests no-std
        run: cargo test --verbose --target-dir=target/no-std --no-default-features --lib --tests --no-run
      - name: Run tests no-std
        run: cargo test --verbose --target-dir=target/no-std --no-default-features --lib --tests

      - name: Clippy
        run: cargo clippy --features std --tests --lib -- -W clippy::all
        env:
          RUSTFLAGS: -D warnings
      - name: Rustup toolchain install nightly
        run: rustup toolchain install nightly
      - name: Set minimal versions
        run: cargo +nightly update -Z minimal-versions
      - name: Build tests (minimal versions)
        run: cargo +stable test --verbose --no-run
      - name: Run tests (minimal versions)
        run: cargo +stable test --verbose
      - uses: taiki-e/install-action@cargo-hack
      - name: Check msrv
        run: cargo hack check --rust-version --workspace --all-targets --ignore-private
